//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AuthenticationEntities : DbContext
    {
        public AuthenticationEntities()
            : base("name=AuthenticationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Dept> tbl_Dept { get; set; }
        public virtual DbSet<tbl_Emp> tbl_Emp { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
